export function SystemDesignIcon({
  className = "h-5 w-5",
}: {
  className?: string;
}) {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
    >
      <rect
        x="3"
        y="3"
        width="7"
        height="7"
        rx="1"
        stroke="currentColor"
        strokeWidth="1.5"
        fill="none"
      />
      <rect
        x="14"
        y="3"
        width="7"
        height="7"
        rx="1"
        stroke="currentColor"
        strokeWidth="1.5"
        fill="none"
      />
      <rect
        x="3"
        y="14"
        width="7"
        height="7"
        rx="1"
        stroke="currentColor"
        strokeWidth="1.5"
        fill="none"
      />
      <rect
        x="14"
        y="14"
        width="7"
        height="7"
        rx="1"
        stroke="currentColor"
        strokeWidth="1.5"
        fill="none"
      />
      <line
        x1="10"
        y1="6.5"
        x2="14"
        y2="6.5"
        stroke="currentColor"
        strokeWidth="1"
      />
      <line
        x1="6.5"
        y1="10"
        x2="6.5"
        y2="14"
        stroke="currentColor"
        strokeWidth="1"
      />
      <line
        x1="17.5"
        y1="10"
        x2="17.5"
        y2="14"
        stroke="currentColor"
        strokeWidth="1"
      />
      <line
        x1="10"
        y1="17.5"
        x2="14"
        y2="17.5"
        stroke="currentColor"
        strokeWidth="1"
      />
    </svg>
  );
}
