import type {
  InterviewQuestionsMap,
  InterviewResourcesMap,
} from "../interviewTypes";

export const dockerQuestions: InterviewQuestionsMap["Docker"] = {
  icon: "🐳",
  sections: [
    {
      title: "Docker Fundamentals",
      questions: [
        {
          question: "What is Docker and what problem does it solve?",
          answer: {
            text: "Docker uses OS-level virtualization to deliver software in packages called containers. Solves the 'it works on my machine' problem by ensuring consistent application behavior across all environments (dev, test, production).",
          },
        },
        {
          question: "Differentiate between Docker Image and Container",
          answer: {
            text: "Docker Image: Read-only template with instructions for creating containers. Contains application code, libraries, dependencies, and configuration. Built from Dockerfile and stored in registry.\n\nDocker Container: Runnable instance of an image. The runtime environment where application executes. An isolated process on the host OS.",
          },
        },
        {
          question: "Explain the Docker Architecture",
          answer: {
            points: [
              "Docker Client: Command-line tool (docker) for user interaction",
              "Docker Daemon (Engine): Background service managing images, containers, networks, and volumes",
              "Docker Registry: Centralized store for Docker images (e.g., Docker Hub)",
            ],
          },
        },
      ],
    },
    {
      title: "Docker Operations",
      questions: [
        {
          question: "What is a Dockerfile and what are best practices?",
          answer: {
            text: "A Dockerfile contains all commands to assemble an image.",
            points: [
              "Use Multi-stage Builds: Separate build-time from runtime dependencies",
              "Use specific base image: FROM node:20-alpine instead of FROM node:latest",
              "Minimize Layers: Chain commands with && to reduce layers",
              "Use .dockerignore: Exclude unnecessary files like .git, node_modules",
            ],
            code: `FROM node:20-alpine AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --only=production\n\nFROM node:20-alpine\nWORKDIR /app\nCOPY --from=builder /app/node_modules ./node_modules\nCOPY . .\nEXPOSE 3000\nCMD ["node", "server.js"]`,
            language: "dockerfile",
          },
        },
        {
          question: "What is Docker Compose and when is it used?",
          answer: {
            text: "Docker Compose defines and runs multi-container Docker applications using a YAML file (docker-compose.yml). Used for local development, testing, and staging environments with multiple interconnected services (web app, database, message queue).",
          },
        },
        {
          question: "Explain Docker Volumes",
          answer: {
            text: "Docker Volumes are the preferred mechanism for persisting data generated by containers.",
            points: [
              "Managed by Docker and stored outside container's file system",
              "Independent of container's lifecycle",
              "Data persists even when container is stopped or deleted",
              "Can share data between containers",
            ],
          },
        },
      ],
    },
  ],
};

export const dockerResources: InterviewResourcesMap["Docker"] = {
  icon: "🐳",
  resources: [
    {
      title: "InterviewBit - Docker Questions",
      description:
        "Containers, images, Dockerfile commands, restart policies, Docker networking",
      url: "https://www.interviewbit.com/docker-interview-questions/",
      type: "Free",
    },
  ],
  keyTopics: [
    "Docker Architecture",
    "Dockerfile",
    "Docker Compose",
    "Networking",
    "Container Orchestration",
  ],
};

